/**
 * Schema.gs — the workbook is generated by code.
 *
 * setupWorkbook() is idempotent: it creates missing tabs, restores deleted columns, rewrites
 * formula columns, reapplies dropdowns, conditional formatting and protection, and never destroys
 * user-entered rows. Running it twice is harmless.
 *
 * Column ORDER is part of the contract — the formulas below reference columns positionally.
 */

const TAB = {
  README: 'README',
  SETTINGS: 'Settings',
  SCENARIOS: 'Scenarios',
  ACCOUNTS: 'Accounts',
  PEOPLE: 'People',
  COURSES: 'Courses',
  ENROLLMENTS: 'Enrollments',
  PERSONA_STATES: 'PersonaStates',
  TICKET_CATEGORIES: 'TicketCategories',
  TICKETS: 'Tickets',
  DEALS: 'Deals',
  MANIFEST: '_Manifest',
  VALIDATION: '_Validation',
  LOG: '_Log',
  PREVIEW: '_Preview'
};

/** Last row of the authored data ranges. 200 data rows is far more than any scenario needs. */
const LAST_ROW = 201;

const ENUM = {
  USE_CASE: ['uc1', 'uc2', 'uc3'],
  // "all" exists for the person doing a full ACME seed. Day to day, everyone works in their own
  // scenario so that Reset and Refresh cannot reach across into someone else's data.
  USE_CASE_SCOPE: ['uc1', 'uc2', 'uc3', 'all'],
  SCENARIO_STATUS: ['designing', 'seeding', 'testing', 'ready'],
  COHORT: ['in_flight', 'established'],
  PLAN_TIER: ['Essentials', 'Growth', 'Enterprise'],
  AUDIENCE: ['all', 'admins'],
  STATUS: ['completed', 'in_progress', 'not_started'],
  ANCHOR_MODE: ['today', 'pinned'],
  ENVIRONMENT: ['test', 'demo'],
  SEVERITY: ['error', 'warning'],
  PLATFORM: ['learnupon', 'hubspot'],
  CLASS: ['persistent', 'disposable', 'schema'],
  PRIORITY: ['LOW', 'MEDIUM', 'HIGH'],
  DEAL_TYPE: ['new', 'renewal', 'expansion']
};

const SETTINGS_DEFAULTS = [
  ['active_use_case', 'uc1', 'WHICH SCENARIO YOU ARE WORKING ON. Seed, Reset, Refresh, Verify and Preview all act on this one only, so you cannot touch a colleague\'s data by accident. Set to "all" only for a full seed.'],
  ['environment', 'test', 'Which portal writes target. test = throwaway portal, demo = ACME.'],
  ['demo_tag', 'MCP-DEMO', 'Written to the demo_source user field so a human can spot our records.'],
  ['t_anchor_mode', 'today', 'today = T is the date of the run. pinned = use t_anchor_date.'],
  ['t_anchor_date', '', 'ISO date (YYYY-MM-DD). Only used when t_anchor_mode = pinned.'],
  ['prng_seed', '20260804', 'Change this to reshuffle every jittered date. Same seed = same output.'],
  ['job_title_field_label', 'Job Title', 'Label of the free-text custom user field holding job title.'],
  ['demo_source_field_label', 'demo_source', 'Label of the free-text custom user field used for tagging.'],
  ['group_title_prefix', 'Customer: ', 'Prefix for LearnUpon group titles. Reads naturally in a demo.'],
  ['course_ref_prefix', 'MCPDEMO', 'Prefix for course reference_code, our invisible course tag.'],
  ['course_owner_id', '', 'LearnUpon user id that owns created courses. Required by POST /courses.']
];

/**
 * Every tab except README and Settings, which have bespoke layouts.
 * col fields: h = header, w = width, list = dropdown values, ref = dropdown sourced from a range,
 * check = checkbox, f = formula template ({r} is substituted with the row number), note = header note.
 */
function tabSpecs() {
  return [
    {
      name: TAB.SCENARIOS,
      cols: [
        { h: 'use_case', w: 80, list: ENUM.USE_CASE },
        { h: 'scenario_name', w: 260 },
        { h: 'owner_name', w: 140, note: 'Who owns this scenario. Named in every confirmation dialog, so you know whose data you are about to change.' },
        { h: 'owner_email', w: 220 },
        { h: 'status', w: 110, list: ENUM.SCENARIO_STATUS },
        { h: 'notes', w: 380 }
      ]
    },
    {
      name: TAB.ACCOUNTS,
      cols: [
        { h: 'account_key', w: 120, note: 'Stable key. Used in identity strings, so changing it rebuilds that account.' },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'company_name', w: 200 },
        { h: 'domain', w: 190, note: 'Filler learner emails are generated at this domain.' },
        { h: 'industry', w: 150 },
        { h: 'cohort', w: 110, list: ENUM.COHORT, note: 'in_flight = mid-onboarding. established = already live.' },
        { h: 'plan_tier', w: 105, list: ENUM.PLAN_TIER },
        { h: 'arr', w: 85 },
        { h: 'onboarding_start_offset', w: 155, note: 'Defines S for this account. Must be T-based, e.g. T-68.' },
        { h: 'target_go_live_offset', w: 150, note: 'Defines G. T- or S-based, e.g. T+12 or S+31.' },
        { h: 'actual_go_live_offset', w: 150, note: 'Established accounts only. Blank for in_flight.' },
        { h: 'user_count', w: 90, note: 'Total users including admins.' },
        { h: 'admin_count', w: 95 },
        { h: 'required_complete_target', w: 165, note: 'Percentage you intend this account to land on.' },
        { h: 'required_complete_actual', w: 160, f: '=IF(LEN($A{r})=0,"",IFERROR(ROUND(100*SUMIF(EnrollAccount,$A{r},EnrollCompleted)/SUMIF(EnrollAccount,$A{r},EnrollCount),0),""))', note: 'Computed live from the Enrollments tab. This is the number the demo will show.' },
        { h: 'csm_owner_email', w: 190 },
        { h: 'lu_group_title', w: 210, f: '=IF(LEN($C{r})=0,"",GroupTitlePrefix&$C{r})', note: 'Computed. The LearnUpon group title, and the demo\'s required-training denominator.' },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.PEOPLE,
      cols: [
        { h: 'person_key', w: 130 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'first_name', w: 110 },
        { h: 'last_name', w: 110 },
        { h: 'email', w: 240, f: '=IF(LEN($C{r})=0,"",LOWER($C{r}&"."&$D{r}&"@"&IFERROR(VLOOKUP($H{r},AccountsKeyDomain,4,FALSE),"MISSING-ACCOUNT")))', note: 'Computed, never typed. A hand-typed email silently breaks the cross-system join.' },
        { h: 'job_title', w: 200, note: 'Written to the job title custom user field. Story 3 depends on this.' },
        { h: 'is_admin', w: 80, check: true, note: 'Admins are the people who block go-live.' },
        { h: 'account_key', w: 130, ref: [TAB.ACCOUNTS, 1] },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.COURSES,
      cols: [
        { h: 'course_key', w: 175 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'title', w: 260, note: 'Appears verbatim in demo answers. Keep it clean, avoid apostrophes.' },
        { h: 'reference_code', w: 190, f: '=IF(LEN($A{r})=0,"",CourseRefPrefix&"-"&UPPER($A{r}))', note: 'Computed. Our invisible course tag.' },
        { h: 'source_module_id', w: 160, note: 'Module to attach as this course\'s content. Must NOT be an "ilt session" — live sessions have their own seat capacity and every enrollment fails with "course capacity reached". SCORM is the safe choice. Verify with Setup -> Check Course Source.' },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.ENROLLMENTS,
      cols: [
        { h: 'row_id', w: 70 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'account_key', w: 130, ref: [TAB.ACCOUNTS, 1] },
        { h: 'course_key', w: 175, ref: [TAB.COURSES, 1] },
        { h: 'audience', w: 90, list: ENUM.AUDIENCE, note: 'all = every user at the account. admins = admins only.' },
        { h: 'enroll_count_override', w: 150, note: 'Leave blank to enrol the whole audience. Set a number to enrol only some of them — 16 of 18 learners, or 0 for "this account enrolled nobody", which is a finding in its own right.' },
        { h: 'enroll_count', w: 105, f: '=IF(LEN($F{r})>0,$F{r},IF(OR(LEN($C{r})=0,LEN($E{r})=0),"",IFERROR(VLOOKUP($C{r},AccountsAll,IF($E{r}="admins",13,12),FALSE),"?")))', note: 'Computed: the override if set, otherwise the account headcount.' },
        { h: 'completed_count', w: 130 },
        { h: 'in_progress_count', w: 140 },
        { h: 'not_started_count', w: 140, f: '=IF(LEN($G{r})=0,"",MAX(0,$G{r}-N($H{r})-N($I{r})))', note: 'Computed remainder.' },
        { h: 'due_offset', w: 130, note: 'Token or range, e.g. G-40..G-5. Ranges jitter per person, so overdue counts emerge from the data.' },
        { h: 'complete_offset', w: 145, note: 'When completions land, e.g. S+10..S+55.' },
        { h: 'in_progress_pct', w: 130, note: 'Number or range, e.g. 15..70.' },
        { h: 'last_access_offset', w: 155, note: 'Last activity for in-progress enrollments, e.g. T-30..T-3.' },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.PERSONA_STATES,
      cols: [
        { h: 'row_id', w: 70 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'person_key', w: 130, ref: [TAB.PEOPLE, 1] },
        { h: 'course_key', w: 175, ref: [TAB.COURSES, 1] },
        { h: 'status', w: 120, list: ENUM.STATUS },
        { h: 'percentage', w: 95, note: 'in_progress only.' },
        { h: 'complete_offset', w: 145, note: 'completed only.' },
        { h: 'last_access_offset', w: 155, note: 'in_progress only.' },
        { h: 'notes', w: 300 }
      ]
    },
    {
      name: TAB.TICKET_CATEGORIES,
      cols: [
        { h: 'category_key', w: 160 },
        { h: 'label', w: 220 },
        { h: 'course_key', w: 175, ref: [TAB.COURSES, 1], note: 'Blank when this is a deliberate content gap.' },
        { h: 'is_deliberate_gap', w: 140, check: true, note: 'TRUE means we must NOT have training for it. Protected by validation.' },
        { h: 'subject_templates', w: 420, note: 'Pipe-separated ticket subjects, picked deterministically per ticket. These appear verbatim in demo answers, so write them the way a real customer would.' },
        { h: 'notes', w: 300 }
      ]
    },
    {
      name: TAB.TICKETS,
      inert: true,
      cols: [
        { h: 'row_id', w: 70 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'account_key', w: 130, ref: [TAB.ACCOUNTS, 1] },
        { h: 'category_key', w: 160, ref: [TAB.TICKET_CATEGORIES, 1] },
        { h: 'window_start', w: 110 },
        { h: 'window_end', w: 110 },
        { h: 'count', w: 70 },
        { h: 'contact_person_keys', w: 200, note: 'Comma-separated, rotated round-robin.' },
        { h: 'priority', w: 90, list: ENUM.PRIORITY },
        { h: 'status', w: 120 },
        { h: 'resolution_hours', w: 130 },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.DEALS,
      inert: true,
      cols: [
        { h: 'row_id', w: 70 },
        { h: 'use_case', w: 75, list: ENUM.USE_CASE },
        { h: 'account_key', w: 130, ref: [TAB.ACCOUNTS, 1] },
        { h: 'pipeline', w: 160 },
        { h: 'stage', w: 160 },
        { h: 'amount', w: 100 },
        { h: 'close_offset', w: 120 },
        { h: 'deal_type', w: 110, list: ENUM.DEAL_TYPE },
        { h: 'notes', w: 260 }
      ]
    },
    {
      name: TAB.MANIFEST,
      owned: true,
      cols: [
        { h: 'run_id', w: 150 }, { h: 'created_at', w: 160 },
        { h: 'platform', w: 100 }, { h: 'object_type', w: 130 },
        { h: 'class', w: 105 }, { h: 'external_id', w: 130 },
        { h: 'natural_key', w: 320 }, { h: 'use_case', w: 75 },
        { h: 'parent_external_id', w: 145 }, { h: 'extra', w: 260 },
        { h: 'environment', w: 110, note: 'Which portal this record lives in. External ids are per-portal, so every read is scoped to Settings.environment.' }
      ]
    },
    {
      name: TAB.VALIDATION,
      owned: true,
      cols: [
        { h: 'checked_at', w: 160 }, { h: 'severity', w: 90 },
        { h: 'tab', w: 140 }, { h: 'row', w: 60 },
        { h: 'column', w: 170 }, { h: 'message', w: 640 }
      ]
    },
    {
      name: TAB.LOG,
      owned: true,
      cols: [
        { h: 'timestamp', w: 160 }, { h: 'run_id', w: 150 },
        { h: 'action', w: 180 }, { h: 'phase', w: 130 },
        { h: 'platform', w: 100 }, { h: 'object_type', w: 130 },
        { h: 'intended', w: 85 }, { h: 'succeeded', w: 90 },
        { h: 'failed', w: 70 }, { h: 'notes', w: 420 }
      ]
    },
    {
      name: TAB.PREVIEW,
      owned: true,
      cols: [
        { h: 'generated_at', w: 160 }, { h: 'platform', w: 100 },
        { h: 'object_type', w: 130 }, { h: 'use_case', w: 75 },
        { h: 'account_key', w: 130 }, { h: 'natural_key', w: 330 },
        { h: 'detail', w: 560 }
      ]
    }
  ];
}

// ---------------------------------------------------------------------------
// setupWorkbook
// ---------------------------------------------------------------------------

function setupWorkbook() {
  const ss = SpreadsheetApp.getActive();
  const specs = tabSpecs();

  ensureSettingsTab_(ss);
  specs.forEach(spec => ensureTab_(ss, spec));
  ensureScenarioRows_(ss);
  ensureReadmeTab_(ss);

  // Named ranges must exist before validation and formulas reference them.
  buildNamedRanges_(ss);
  specs.forEach(spec => {
    applyValidation_(ss, spec);
    applyFormulas_(ss, spec);
  });

  applyConditionalFormatting_(ss);
  specs.filter(s => s.owned).forEach(s => protectTab_(ss.getSheetByName(s.name)));
  orderTabs_(ss, specs);

  SpreadsheetApp.getActive().toast('Workbook created / repaired.', 'MCP Demo Seeder', 5);
}

function ensureTab_(ss, spec) {
  let sh = ss.getSheetByName(spec.name);
  if (!sh) sh = ss.insertSheet(spec.name);
  reconcileHeaders_(sh, spec.cols);

  sh.setFrozenRows(1);
  const width = spec.cols.length;
  const header = sh.getRange(1, 1, 1, width);
  header.setFontWeight('bold').setBackground('#1d4ed8').setFontColor('#ffffff').setVerticalAlignment('middle');
  sh.setRowHeight(1, 30);
  spec.cols.forEach((c, i) => {
    if (c.w) sh.setColumnWidth(i + 1, c.w);
    const cell = sh.getRange(1, i + 1);
    if (c.note) cell.setNote(c.note);
    if (c.f) cell.setBackground('#475569'); // computed columns read as "don't type here"
  });
  if (sh.getMaxRows() < LAST_ROW) sh.insertRowsAfter(sh.getMaxRows(), LAST_ROW - sh.getMaxRows());
  return sh;
}

/**
 * Restores columns someone deleted, without disturbing their data. If a spec header is missing
 * entirely we insert a column in the right position; extra trailing columns are left alone so
 * people can keep their own scratch notes.
 */
function reconcileHeaders_(sh, cols) {
  if (sh.getMaxColumns() < cols.length) {
    sh.insertColumnsAfter(sh.getMaxColumns(), cols.length - sh.getMaxColumns());
  }
  for (let i = 0; i < cols.length; i++) {
    const existing = sh.getRange(1, 1, 1, sh.getMaxColumns()).getValues()[0].map(v => String(v).trim());
    if (existing[i] === cols[i].h) continue;
    // A non-empty header we don't recognise here means a column was deleted and everything
    // shifted left — reinsert, so the row's data lines up with its headers again.
    if (existing[i] !== '' && existing.indexOf(cols[i].h) === -1) sh.insertColumnBefore(i + 1);
    sh.getRange(1, i + 1).setValue(cols[i].h);
  }
  // Assert the spec headers, so a renamed header snaps back.
  sh.getRange(1, 1, 1, cols.length).setValues([cols.map(c => c.h)]);
}

/** Seeds one row per scenario the first time, so ownership is visible from day one. */
function ensureScenarioRows_(ss) {
  const sh = ss.getSheetByName(TAB.SCENARIOS);
  if (sh.getLastRow() > 1) return;   // never overwrite what people have filled in
  sh.getRange(2, 1, 3, 6).setValues([
    ['uc1', 'Customer Onboarding Health', '', '', 'testing',
     'In-flight accounts behind on required training, plus an established cohort that proves the correlation.'],
    ['uc2', 'Knowledge Gaps vs Support Tickets', '', '', 'designing',
     'Ticket categories with no course are the content roadmap. Depends on the deliberate gaps staying empty.'],
    ['uc3', 'Upsell and Renewal Readiness', '', '', 'designing',
     'Learners taking courses outside their plan tier, with a renewal approaching.']
  ]);
}

function ensureSettingsTab_(ss) {
  let sh = ss.getSheetByName(TAB.SETTINGS);
  if (!sh) sh = ss.insertSheet(TAB.SETTINGS);
  sh.getRange(1, 1, 1, 3).setValues([['key', 'value', 'notes']])
    .setFontWeight('bold').setBackground('#1d4ed8').setFontColor('#ffffff');
  sh.setFrozenRows(1);
  sh.setColumnWidth(1, 210).setColumnWidth(2, 220).setColumnWidth(3, 560);

  const existing = {};
  const last = Math.max(sh.getLastRow(), 1);
  if (last > 1) {
    sh.getRange(2, 1, last - 1, 2).getValues().forEach((r, i) => {
      if (String(r[0]).trim()) existing[String(r[0]).trim()] = { value: r[1], row: i + 2 };
    });
  }
  let row = last + 1;
  SETTINGS_DEFAULTS.forEach(([key, dflt, note]) => {
    if (existing[key]) {
      sh.getRange(existing[key].row, 3).setValue(note); // notes are ours; values are theirs
      return;
    }
    sh.getRange(row, 1, 1, 3).setValues([[key, dflt, note]]);
    row++;
  });

  applyListValidation_(sh, 'environment', ENUM.ENVIRONMENT);
  applyListValidation_(sh, 't_anchor_mode', ENUM.ANCHOR_MODE);
  applyListValidation_(sh, 'active_use_case', ENUM.USE_CASE_SCOPE);
}

function applyListValidation_(settingsSheet, key, values) {
  const rows = settingsSheet.getRange(2, 1, Math.max(settingsSheet.getLastRow() - 1, 1), 1).getValues();
  for (let i = 0; i < rows.length; i++) {
    if (String(rows[i][0]).trim() === key) {
      settingsSheet.getRange(i + 2, 2).setDataValidation(
        SpreadsheetApp.newDataValidation().requireValueInList(values, true).setAllowInvalid(false).build());
      return;
    }
  }
}

function buildNamedRanges_(ss) {
  const settings = ss.getSheetByName(TAB.SETTINGS);
  const keys = settings.getRange(2, 1, Math.max(settings.getLastRow() - 1, 1), 1).getValues()
    .map(r => String(r[0]).trim());
  const settingCell = key => {
    const i = keys.indexOf(key);
    return i === -1 ? null : settings.getRange(i + 2, 2);
  };

  const ranges = {
    AccountsAll: ss.getSheetByName(TAB.ACCOUNTS).getRange(2, 1, LAST_ROW - 1, 18),
    AccountsKeyDomain: ss.getSheetByName(TAB.ACCOUNTS).getRange(2, 1, LAST_ROW - 1, 4),
    AccountKeys: ss.getSheetByName(TAB.ACCOUNTS).getRange(2, 1, LAST_ROW - 1, 1),
    EnrollAccount: ss.getSheetByName(TAB.ENROLLMENTS).getRange(2, 3, LAST_ROW - 1, 1),
    EnrollCount: ss.getSheetByName(TAB.ENROLLMENTS).getRange(2, 7, LAST_ROW - 1, 1),
    EnrollCompleted: ss.getSheetByName(TAB.ENROLLMENTS).getRange(2, 8, LAST_ROW - 1, 1),
    GroupTitlePrefix: settingCell('group_title_prefix'),
    CourseRefPrefix: settingCell('course_ref_prefix')
  };

  const byName = {};
  ss.getNamedRanges().forEach(nr => { byName[nr.getName()] = nr; });
  Object.keys(ranges).forEach(name => {
    if (!ranges[name]) return;
    if (byName[name]) byName[name].setRange(ranges[name]);
    else ss.setNamedRange(name, ranges[name]);
  });
}

function applyValidation_(ss, spec) {
  const sh = ss.getSheetByName(spec.name);
  spec.cols.forEach((c, i) => {
    const range = sh.getRange(2, i + 1, LAST_ROW - 1, 1);
    if (c.f || spec.owned) { range.clearDataValidations(); return; }
    let rule = null;
    if (c.list) {
      rule = SpreadsheetApp.newDataValidation().requireValueInList(c.list, true).setAllowInvalid(false)
        .setHelpText('One of: ' + c.list.join(', ')).build();
    } else if (c.check) {
      rule = SpreadsheetApp.newDataValidation().requireCheckbox().build();
    } else if (c.ref) {
      const src = ss.getSheetByName(c.ref[0]).getRange(2, c.ref[1], LAST_ROW - 1, 1);
      rule = SpreadsheetApp.newDataValidation().requireValueInRange(src, true).setAllowInvalid(false)
        .setHelpText('Must match a key on the ' + c.ref[0] + ' tab').build();
    }
    if (rule) range.setDataValidation(rule); else range.clearDataValidations();
  });
}

function applyFormulas_(ss, spec) {
  const sh = ss.getSheetByName(spec.name);
  spec.cols.forEach((c, i) => {
    if (!c.f) return;
    const formulas = [];
    for (let r = 2; r <= LAST_ROW; r++) formulas.push([c.f.replace(/\{r\}/g, String(r))]);
    sh.getRange(2, i + 1, formulas.length, 1).setFormulas(formulas);
  });
}

function applyConditionalFormatting_(ss) {
  // _Validation: errors red, warnings amber.
  const v = ss.getSheetByName(TAB.VALIDATION);
  v.setConditionalFormatRules([
    SpreadsheetApp.newConditionalFormatRule().whenTextEqualTo('error')
      .setBackground('#fee2e2').setFontColor('#991b1b')
      .setRanges([v.getRange(2, 1, LAST_ROW - 1, 6)]).build(),
    SpreadsheetApp.newConditionalFormatRule().whenTextEqualTo('warning')
      .setBackground('#fef3c7').setFontColor('#92400e')
      .setRanges([v.getRange(2, 1, LAST_ROW - 1, 6)]).build()
  ]);

  // Accounts: flag when the number the demo will actually show drifts from the intended one.
  const a = ss.getSheetByName(TAB.ACCOUNTS);
  a.setConditionalFormatRules([
    SpreadsheetApp.newConditionalFormatRule()
      .whenFormulaSatisfied('=AND(LEN($N2)>0,LEN($O2)>0,ABS($N2-$O2)>2)')
      .setBackground('#fee2e2').setFontColor('#991b1b')
      .setRanges([a.getRange(2, 14, LAST_ROW - 1, 2)]).build()
  ]);

  // TicketCategories: deliberate gaps must be visually obvious so nobody fills one in by accident.
  const tc = ss.getSheetByName(TAB.TICKET_CATEGORIES);
  tc.setConditionalFormatRules([
    SpreadsheetApp.newConditionalFormatRule().whenFormulaSatisfied('=$D2=TRUE')
      .setBackground('#ede9fe').setFontColor('#5b21b6')
      .setRanges([tc.getRange(2, 1, LAST_ROW - 1, 5)]).build()
  ]);
}

function protectTab_(sh) {
  if (!sh) return;
  sh.getProtections(SpreadsheetApp.ProtectionType.SHEET).forEach(p => p.remove());
  sh.protect().setDescription('Script-owned. Do not edit by hand.').setWarningOnly(true);
  sh.setTabColor('#94a3b8');
}

function orderTabs_(ss, specs) {
  const order = [TAB.README, TAB.SETTINGS].concat(specs.map(s => s.name));
  order.forEach((name, i) => {
    const sh = ss.getSheetByName(name);
    if (!sh) return;
    ss.setActiveSheet(sh);
    ss.moveActiveSheet(i + 1);
  });
  ss.setActiveSheet(ss.getSheetByName(TAB.README));
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function ensureReadmeTab_(ss) {
  let sh = ss.getSheetByName(TAB.README);
  if (!sh) sh = ss.insertSheet(TAB.README);
  sh.clear();
  sh.getProtections(SpreadsheetApp.ProtectionType.SHEET).forEach(p => p.remove());
  sh.setColumnWidth(1, 940);
  sh.setHiddenGridlines(true);

  const blocks = [
    ['MCP Demo Data Seeder', 'h1'],
    ['Seeds, refreshes and safely removes demo data in LearnUpon (HubSpot later) so an AI assistant querying them via MCP can answer questions about training-driven outcomes.', 'p'],

    ['How to run a seed', 'h2'],
    ['1.  Setup -> Create / Repair Workbook  (safe to re-run any time)\n' +
     '2.  Setup -> Set Credentials, then Check Credentials\n' +
     '3.  Author the reference tabs, or Setup -> Load Example Scenario (UC1)\n' +
     '4.  Validate  -- seeding is blocked while any error exists\n' +
     '5.  Preview (dry run)  -- writes the full plan to _Preview without touching any platform\n' +
     '6.  Seed, one phase at a time  (added in a later build phase)', 'pre'],

    ['The T-scale convention', 'h2'],
    ['Dates are never typed literally. They are offsets from an anchor, resolved when you run:\n\n' +
     '   T, T+n, T-n     the global anchor (today, or Settings.t_anchor_date when pinned)\n' +
     '   S, S+n, S-n     that account\'s onboarding start date\n' +
     '   G, G+n, G-n     that account\'s target go-live date\n\n' +
     'Any offset cell also accepts a range, written A..B, e.g.  G-40..G-5\n' +
     'Each record gets its own date inside that window, so overdue counts emerge from the data\n' +
     'instead of being declared. Same seed = same dates, every time.', 'pre'],

    ['What each tab is for', 'h2'],
    ['Settings           environment, anchor mode, seed, custom-field labels\n' +
     'Accounts           the companies. Headcount, cohort, onboarding and go-live dates\n' +
     'People             named personas only. Fillers are generated, not listed\n' +
     'Courses            the required training, and which course to clone from\n' +
     'Enrollments        one row per account x course: how many complete, in progress, not started\n' +
     'PersonaStates      pin a named person to a specific state, e.g. "Dana has not started"\n' +
     'TicketCategories   ticket taxonomy, including the deliberate content gaps\n' +
     'Tickets, Deals     authored now, inert until HubSpot is connected', 'pre'],

    ['Columns with a dark grey header are computed', 'h3'],
    ['Do not type in them — Create / Repair Workbook will overwrite whatever you put there. Notably, People.email is computed from first name, last name and the account domain. A hand-typed email that does not match its HubSpot contact would silently break the cross-system join and would probably survive until demo day.', 'p'],

    ['Tabs beginning with an underscore are script-owned', 'h3'],
    ['_Manifest is the ledger of every record we created, and the ONLY authority for deletion. Reset never searches a platform for things to delete — if a record is not in the manifest, it is not touched. Read it before authorizing a reset.', 'p'],

    ['Two portals', 'h2'],
    ['Settings.environment selects which portal writes go to: "test" for the throwaway portal, "demo" for ACME. Credentials for both live in Script Properties. Every write dialog tells you which portal it is about to hit — read it.', 'p'],

    ['Credentials access caveat', 'h3'],
    ['Credentials are stored in Script Properties, never in a cell. But anyone with edit access to this sheet can open the script editor and read them. That is an accepted trade-off for demo-portal credentials shared among the project team — it is recorded here so it is not a surprise.', 'p'],

    ['Safety guarantees', 'h2'],
    ['Reset deletes enrollments and nothing else. Users, groups, memberships and courses are created once and are never removed by this toolkit. No code path can delete a user, or any record absent from _Manifest. Deletes verify the record\'s tag first and skip anything that fails the check.', 'p'],

    ['One invariant worth knowing', 'h3'],
    ['A seeded user must never be enrolled in a course outside their use case\'s required set. The demo computes "percent of required training complete" from a group-filtered progress report, so a stray enrollment silently changes every percentage in the story.', 'p']
  ];

  let row = 1;
  blocks.forEach(([text, kind]) => {
    const cell = sh.getRange(row, 1);
    cell.setValue(text).setVerticalAlignment('top');
    if (kind === 'h1') cell.setFontSize(20).setFontWeight('bold').setFontColor('#1d4ed8');
    if (kind === 'h2') cell.setFontSize(14).setFontWeight('bold').setFontColor('#1e293b');
    if (kind === 'h3') cell.setFontSize(11).setFontWeight('bold').setFontColor('#334155');
    if (kind === 'p') cell.setWrap(true).setFontColor('#334155');
    if (kind === 'pre') cell.setFontFamily('Courier New').setFontSize(10).setFontColor('#0f172a');
    row += (kind === 'h1' || kind === 'h2') ? 2 : 1;
    if (kind === 'p' || kind === 'pre') row += 1;
  });
  sh.setTabColor('#1d4ed8');
}
